kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: monitoring-influxdb
  namespace: kube-system
  labels:
    task: monitoring
    k8s-app: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      nodeSelector:
        kubernetes.io/hostname: kuben0
      volumes:
        - name: influxdb-storage
          emptyDir: {}
        - name: influxdb-config
          hostPath:
            path: /etc/influxdb
      containers:
        - name: influxdb
          image: influxdb:1.2.0-rc1-alpine
          ports:
            - name: api
              containerPort: 8086
            - name: admin
              containerPort: 8083
          args:
            - -config 
            - /etc/influxdb/influxdb.conf
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-storage
            - mountPath: /etc/influxdb
              name: influxdb-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: api
      port: 8086
      targetPort: 8086
    - name: admin
      port: 8083
      targetPort: 8083
  selector:
    k8s-app: influxdb